---
# tasks file for deploy-zabbix-agent

- name: Create a log directory if it does not exist
  file:
    path: /var/log/zabbix-agent/
    state: directory
    mode: '0755'
  become: yes

# Zabbix repo deb 10

- name: check if already installed
  command: dpkg-query -W zabbix-release
  register: zabbix_release_check_deb
  failed_when: zabbix_release_check_deb.rc > 1
  changed_when: zabbix_release_check_deb.rc == 1
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == Ubuntu

- name: Download zabbix-release
  get_url:
    url='http://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bbuster_all.deb'
    dest='/home/{{ ansible_env.USER }}/Downloads/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == Ubuntu

- name: Install zabbix-release
  become: yes
  apt:
    deb='/home/{{ ansible_env.USER }}/Downloads/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == Ubuntu

# Install agent 2

- name: Install Zabbix-agent (Debian)
  apt:
    name:
      - zabbix-agent2
    state: present
    update_cache: yes
  become: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: install Zabbix-agent (RHEL 8)
  yum:
    name: https://repo.zabbix.com/zabbix/5/rhel/8/x86_64/zabbix-release-5-1.el8.noarch.rpm
    state: present
  become: yes
  when: (ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat' ) and {{ ansible_distribution_major_version }} == 8

- name: install zabbix-agent (RHEL 7)
  yum:
    name: https://repo.zabbix.com/zabbix/5/rhel/7/x86_64/zabbix-release-5-1.el7.noarch.rpm
    state: present
  become: yes
  when: (ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat' ) and {{ ansible_distribution_major_version }}  == 7

- name: install zabbix-agent (RHEL)
  yum:
    name: zabbix-agent2
    state: present
  become: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'

- name: Configutation for Server/Proxy
  template:
    src: zabbix-agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  

- name: RHEL Firewall
  firewalld:
    port: 10050/tcp
    zone: public
    permanent: true
    state: enabled
  become: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'


- name: RHEL Firewall
  firewalld:
    port: 10051/tcp
    zone: public
    permanent: true
    state: enabled
  become: yes
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'


- name: Check zabbix-agent service
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  become: yes